{{- if eq .Values.ocpconsole.setup "true" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-ocpconsole
  namespace: {{ .Release.Namespace }}
spec:
  host: "{{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.deployer.domain }}"
  path: /console/
  httpHeaders:
    actions:
      response:
      - name: X-Frame-Options
        action:
          type: Set
          set:
            value: SAMEORIGIN
  to:
    kind: Service
    name: {{ .Release.Name }}-ocpconsole
  port:
    targetPort: 9000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
