---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
  namespace: {{- template "namespace.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom
    spec:
      containers:
      - name: showroom
        image: {{ .Values.home.image }}
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
           protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          {{- toYaml .Values.home.resources | nindent 10 }}
        volumeMounts:
        - name: content
          mountPath: {{ .Values.home.contentMount }}
      volumes:
      - name: content
        configMap:
          name: {{ .Values.home.contentConfig }}
